DROP TABLE PIZZA_INGREDIENTS;
DROP TABLE PIZZAS;
DROP TABLE INGREDIENTS;
DROP TABLE DOUGHS;

/*
	Note: 256 byte varchars are used for "short" strings, like names,
	and 512 byte varchars are used for "long" strings, like descriptions.
	INGREDIENTS.TYPE's length is based on the longest possible enum value
*/
CREATE TABLE "DOUGHS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 START WITH 1) NOT NULL, 
	"NAME" VARCHAR2(256 BYTE) NOT NULL, 
	"GRAMS_FLOUR" INT NOT NULL, 
	"GRAMS_WATER" INT NOT NULL, 
	"FLOUR_TYPE" VARCHAR2(256 BYTE) NOT NULL, 
	"WATER_TEMP" INT NOT NULL, 
	"GRAMS_YEAST" INT NOT NULL, 
	"GRAMS_SALT" INT NOT NULL, 
	"GRAMS_SUGAR" INT NOT NULL, 
	"GRAMS_OLIVE_OIL" INT NOT NULL, 
	"BULK_FERMENT_TIME" INT NOT NULL, 
	"PROOF_TIME" INT NOT NULL, 
	"SPECIAL_INSTRUCTIONS" VARCHAR2(512 BYTE), 
	 PRIMARY KEY ("ID")
   );

CREATE TABLE "INGREDIENTS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 START WITH 1) NOT NULL, 
   	"TYPE" VARCHAR2(10 BYTE) NOT NULL, 
	"NAME" VARCHAR2(256 BYTE) NOT NULL, 
	"NOTES" VARCHAR2(256 BYTE), 
	 PRIMARY KEY ("ID"),
	 CHECK ("TYPE" in ('cheese', 'sauce', 'meat', 'vegetable', 'fruit', 'other'))
   );

CREATE TABLE "PIZZAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 START WITH 1) NOT NULL, 
	"DOUGH_ID" NUMBER, 
	"NAME" VARCHAR2(256 BYTE) NOT NULL, 
	"BAKE_TIME" INT NOT NULL, 
	"OVEN_TEMP" INT NOT NULL, 
	"SPECIAL_INSTRUCTIONS" VARCHAR2(512 BYTE), 
	 PRIMARY KEY ("ID"),
	 FOREIGN KEY ("DOUGH_ID") REFERENCES "DOUGHS" ("ID") ON DELETE SET NULL
   );

CREATE TABLE "PIZZA_INGREDIENTS" 
   (	"PIZZA_ID" NUMBER NOT NULL, 
	"INGREDIENT_ID" NUMBER NOT NULL, 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	 UNIQUE ("PIZZA_ID", "INGREDIENT_ID"),
	 FOREIGN KEY ("PIZZA_ID") REFERENCES "PIZZAS" ("ID") ON DELETE CASCADE, 
	 FOREIGN KEY ("INGREDIENT_ID") REFERENCES "INGREDIENTS" ("ID") ON DELETE CASCADE
   );

COMMENT ON TABLE PIZZA_INGREDIENTS IS "A join table for the many-to-many relationship of pizzas to ingredients.";

/* adding some sample data */

INSERT INTO DOUGHS (NAME, GRAMS_FLOUR, GRAMS_WATER, FLOUR_TYPE, WATER_TEMP, GRAMS_YEAST, GRAMS_SALT, GRAMS_SUGAR, GRAMS_OLIVE_OIL, BULK_FERMENT_TIME, PROOF_TIME, SPECIAL_INSTRUCTIONS)
    values ('Sample dough', 500, 400, 'Bread flour', 90, 20, 10, 0, 50, 120, 30, 'Can also proof overnight in the refrigerator');
INSERT INTO DOUGHS (NAME, GRAMS_FLOUR, GRAMS_WATER, FLOUR_TYPE, WATER_TEMP, GRAMS_YEAST, GRAMS_SALT, GRAMS_SUGAR, GRAMS_OLIVE_OIL, BULK_FERMENT_TIME, PROOF_TIME, SPECIAL_INSTRUCTIONS)
    values ('Sample dough 2', 500, 350, '00 Flour', 90, 10, 10, 0, 50, 720, 60, NULL);
INSERT INTO DOUGHS (NAME, GRAMS_FLOUR, GRAMS_WATER, FLOUR_TYPE, WATER_TEMP, GRAMS_YEAST, GRAMS_SALT, GRAMS_SUGAR, GRAMS_OLIVE_OIL, BULK_FERMENT_TIME, PROOF_TIME, SPECIAL_INSTRUCTIONS)
    values ('Sample dough 3', 500, 450, '00 Flour', 90, 5, 10, 0, 50, 1440, 60, NULL);
    
INSERT INTO INGREDIENTS (NAME, TYPE, NOTES)
    values ('Pepperoni', 'meat', NULL);
INSERT INTO INGREDIENTS (NAME, TYPE, NOTES)
    values ('Low moisture mozarella', 'cheese', NULL);
INSERT INTO INGREDIENTS (NAME, TYPE, NOTES)
    values ('Marinara sauce', 'sauce', 'Store bought pizza or marinara sauce is fine');
    
INSERT INTO PIZZAS (NAME, BAKE_TIME, OVEN_TEMP, SPECIAL_INSTRUCTIONS, DOUGH_ID)
    values ('Sample pizza', 10, 500, 'Adjust time if using a cool oven', 1);
INSERT INTO PIZZAS (NAME, BAKE_TIME, OVEN_TEMP, SPECIAL_INSTRUCTIONS, DOUGH_ID)
    values ('Sample pizza 2', 20, 400, NULL, 2);
INSERT INTO PIZZAS (NAME, BAKE_TIME, OVEN_TEMP, SPECIAL_INSTRUCTIONS, DOUGH_ID)
    values ('Sample pizza 3', 30, 350, NULL, 3);
    

INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (1, 1);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (1, 2);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (1, 3);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (2, 1);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (2, 2);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (2, 3);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (3, 1);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (3, 2);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (3, 3);


