DROP TABLE PIZZA_INGREDIENTS;
DROP TABLE PIZZAS;
DROP TABLE INGREDIENTS;
DROP TABLE DOUGHS;

CREATE TABLE "DOUGHS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL, 
	"NAME" VARCHAR2(256 BYTE) NOT NULL, 
	"GRAMS_FLOUR" NUMBER(*,0) NOT NULL, 
	"GRAMS_WATER" NUMBER(*,0) NOT NULL, 
	"FLOUR_TYPE" VARCHAR2(256 BYTE) NOT NULL, 
	"WATER_TEMP" NUMBER(*,0) NOT NULL, 
	"GRAMS_YEAST" NUMBER(*,0) NOT NULL, 
	"GRAMS_SALT" NUMBER(*,0) NOT NULL, 
	"GRAMS_SUGAR" NUMBER(*,0) NOT NULL, 
	"GRAMS_OLIVE_OIL" NUMBER(*,0) NOT NULL, 
	"BULK_FERMENT_TIME" NUMBER(*,0) NOT NULL, 
	"PROOF_TIME" NUMBER(*,0) NOT NULL, 
	"SPECIAL_INSTRUCTIONS" VARCHAR2(512 BYTE), 
	 PRIMARY KEY ("ID")
   );

CREATE TABLE "INGREDIENTS" 
   (	"TYPE" VARCHAR2(20 BYTE) NOT NULL, 
	"NAME" VARCHAR2(256 BYTE) NOT NULL, 
	"NOTES" VARCHAR2(256 BYTE), 
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL, 
	 PRIMARY KEY ("ID"),
	 CHECK ("TYPE" in ('cheese', 'sauce', 'meat', 'vegetable', 'fruit', 'other'))
   );

CREATE TABLE "PIZZAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL, 
	"DOUGH_ID" NUMBER, 
	"NAME" VARCHAR2(256 BYTE) NOT NULL, 
	"BAKE_TIME" NUMBER(*,0), 
	"SPECIAL_INSTRUCTIONS" VARCHAR2(512 BYTE), 
	"OVEN_TEMP" NUMBER(*,0) NOT NULL, 
	 PRIMARY KEY ("ID"),
	 FOREIGN KEY ("DOUGH_ID") REFERENCES "DOUGHS" ("ID") ON DELETE SET NULL
   );

CREATE TABLE "PIZZA_INGREDIENTS" 
   (	"PIZZA_ID" NUMBER NOT NULL, 
	"INGREDIENT_ID" NUMBER NOT NULL, 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	 UNIQUE ("PIZZA_ID", "INGREDIENT_ID"),
	 FOREIGN KEY ("PIZZA_ID") REFERENCES "PIZZAS" ("ID") ON DELETE CASCADE, 
	 FOREIGN KEY ("PIZZA_ID") REFERENCES "INGREDIENTS" ("ID") ON DELETE CASCADE
   );

COMMENT ON TABLE PIZZA_INGREDIENTS IS "A join table for the many-to-many relationship of pizzas to ingredients.";

/* adding some sample data */

INSERT INTO DOUGHS (NAME, GRAMS_FLOUR, GRAMS_WATER, FLOUR_TYPE, WATER_TEMP, GRAMS_YEAST, GRAMS_SALT, GRAMS_SUGAR, GRAMS_OLIVE_OIL, BULK_FERMENT_TIME, PROOF_TIME, SPECIAL_INSTRUCTIONS)
    values ('Sample dough', 500, 400, 'Bread flour', 90, 10, 10, 0, 50, 120, 30, 'Can also proof overnight in the refrigerator');
    
INSERT INTO INGREDIENTS (NAME, TYPE, NOTES)
    values ('Pepperoni', 'meat', NULL);
INSERT INTO INGREDIENTS (NAME, TYPE, NOTES)
    values ('Low moisture mozarella', 'cheese', NULL);
INSERT INTO INGREDIENTS (NAME, TYPE, NOTES)
    values ('Marinara sauce', 'sauce', 'Store bought pizza or marinara sauce is fine');
    
INSERT INTO PIZZAS (NAME, BAKE_TIME, OVEN_TEMP, SPECIAL_INSTRUCTIONS, DOUGH_ID)
    values ('Sample pizza', 10, 500, 'Adjust time if using a cool oven', 1);
    

INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (1, 1);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (1, 2);
INSERT INTO PIZZA_INGREDIENTS (pizza_id, ingredient_id) values (1, 3);
